version: '3'

services:
  shell:
    build:
      context: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    command: /bin/bash
    tty: true
    stdin_open: true

volumes:
  node_modules:
